Lwd/urls.py
#!/Software/Python37
# -*- coding:utf-8 -*-
# 文件: urls
# 作者: lwd
# 时间: 2019/4/20 13:08
# IDE: PyCharm
from django.conf.urls import url

from Lwd import views

app_name = 'lwd'
urlpatterns = [
    # 测试
    url(r'^hello/$', views.hello),

    # 首页
    url(r'^$', views.index, name="index"),
    # url(r'^index/$', views.index, name='index'),

    # 注册
    url(r'^register/$', views.register_get, name="register"),
    url(r'^register_post/$', views.register_post, name="register_post"),
    # 检查账号是否存在
    url(r'^checkaccount/$', views.checkaccount, name="checkaccount"),
    # 检查用户名是否再存
    url(r'^checkname/$', views.checkname, name="checkname"),

    # 登录
    url(r'^login/$', views.login_get, name="login"),
    url(r'^login_post/$', views.login_post, name='login_post'),
    # 退出登录
    url(r'^quit/$', views.quit, name="quit"),
    # 判断用户是否登录
    url(r'^is_login/$', views.is_login, name="is_login"),

    # 写文章
    url(r'^write/$', views.write_article_get, name="write"),
    url(r'^write_post', views.write_article_post, name='write_post'),
    # 上传图片
    url(r'^upload_img/$', views.upload_img, name="upload_img"),

    # 文章详情
    url(r'^a_id/(\w+)/$', views.blog_detail, name="blog_detail"),

    # 核对是否被关注
    url(r'^checkfollow/$', views.check_is_follow, name="checkfollow"),
    # 关注取消
    url(r'^follow_or_cancel/$', views.follow_or_cancel, name="follow_or_cancel"),

    # 喜欢
    url(r'^like_handler/$', views.like_handler, name="like_handler"),
    # 收藏
    url(r'^collect_handler/$', views.collect_handler, name="collect_handler"),
    # 核对是否被喜欢
    url(r'^is_like/$', views.is_like, name='is_like'),
    # 核对是否被收藏
    url(r'^is_collect/$', views.is_collect, name="is_collect"),

    # 我的主页
    url(r'^u_id/(\w+)', views.user_home, name="user_home"),
    # 收藏与喜欢的文章
    url(r'^collect_like/u_id/(\w+)/$', views.collect_like, name="collect_like"),
    # 用户设置
    url(r'^setting/u_id/(\w+)', views.user_setting_get, name='user_setting'),
    # 头像修改
    url(r'^update_avatar/$', views.update_avatar, name="update_avatar"),
    # 基础设置-其他-如用户名、绑定邮箱、语言设置
    url(r'^basic_setting/$', views.basic_setting_other, name="basic_setting"),
    # 个人资料设置
    url(r'^personal_setting/$', views.personal_setting, name='personal_setting'),
    # 账号管理
    # 修改密码
    url(r'^update_pwd/$', views.update_pwd, name="update_pwd"),
    # 删除账号
    url(r'^delete_account/$', views.delete_account, name='delete_account'),

    # 编辑文章
    url(r'^edit/(\w+)/$', views.edit_article_get, name='edit'),
    url(r'^edit_post/', views.edit_article_post, name='edit_post'),
    # 删除文章-逻辑删除
    url(r'^delete_logic/(\w+)/(\w+)/$', views.delete_article_logic, name="delete_article_logic"),
    # 删除草稿-彻底删除
    url(r'^delete_com/(\w+)/(\w+)/$', views.delete_article_complete, name='delete_article_com'),

    # 关于本站
    url(r'^about_me/$', views.about_me, name="about_me"),


    # 搜索页
    # url(r'^search/$', views.lwd_search, name='lwd_search')

    # 文章分类列表
    url(r'^article_category/(?P<pk>[0-9]+)/$', views.article_category, name='article_category'),

    # 归档功能
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),

    # 标签云
    url(r'^article_tag/(?P<pk>[0-9]+)/$', views.article_tag, name='article_tag'),









]

Python_Blog/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from Lwd.feeds import AllPostsRssFeed
from Python_Blog import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^xadmin/', xadmin.site.urls),

    # 首页主要功能
    url(r'', include('Lwd.urls', namespace='lwd')),
    # 评论功能
    url(r'^comments/', include('comments.urls')),
    # 全文检索
    url(r'^search/', include('haystack.urls')),
    # rss订阅
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 新加入

templates/article_category.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}

{% block title %}
    <title>
        Lwd's Blog | {{ a_category_0 }}
    </title>
{% endblock %}

{% block EXTCSS %}
    <link rel="stylesheet" href="{% static 'index/css/index.css' %}">
    <style type="text/css">
        .classify_list_back_home:hover {
            color: #0077DD;
        }
    </style>
{% endblock %}

{% block content %}

    <main>
        <h2 class="place">您现在的位置是：<a class="classify_list_back_home" href="{% url 'lwd:index' %}">网站首页</a> &gt; {{ a_category_0 }}
        </h2>
        {# 博客文章列表 #}
        <div class="bloglist">
            <ul>
                {% for article in article_page %}
                    {# 文章 li begin #}
                    <li>
                        {# 文章图片 #}
                        <i class="blogpic">
                            <a href="{% url 'lwd:blog_detail' article.a_id %}"><img src="{{ MEDIA_URL }}{{ article.a_pre_img }}" alt=""> </a>
                        </i>
                        {# 文章概要内容 #}
                        <dl>
                            {# 标题 #}
                            <dt>
                                <a href="{% url 'lwd:blog_detail' article.a_id %}" target="_blank">
                                    {{ article.a_title }}
                                </a>
                            </dt>

                            <dd>
                                {# 文章内容简要 #}
                                <span class="bloginfo">
                                   {{ article.a_content_text }}
                                </span>

                                <p class="article-otherinfo">
                                    {# 作者 #}
                                    <span class="author">
                                        <a href="{% url 'lwd:user_home' article.a_user_id %}"
                                           target="_blank">{{ article.a_author }}</a>
                                    </span>
                                    {# 时间 #}
                                    <span class="date">{{ article.a_create_time }}</span>
                                    {# 喜欢数量 #}
                                    <span class="like"><i
                                            class="fa fa-heart"></i> {{ article.a_like_num }} </span>
                                    {# 评论数量 #}
                                    <span class="remark"><i
                                            class="fa fa-commenting"></i> {{ article.a_comment_num }}</span>
                                    {# 分类 #}
                                    <span class="lwd-article-class">
                                        <a href="{% url 'lwd:article_category' article.a_category.id %}">{{ article.a_category.category_name }}</a>
                                    </span>
                                </p>
                            </dd>
                        </dl>
                    </li>
                    {# 文章 li end #}
                {% empty %}
                    <p style="margin-bottom: 20px">该分类还没有文章哟</p>
                {% endfor %}
            </ul>
            {# end  bloglist  ul #}
        </div>
        {# end bloglist #}

        {% include 'pagination.html' %}

    </main>

    {# 侧边栏 #}
    <aside class="sidebar">

        {# fenlei-bar begin #}
        <div class="fenlei">
            <ul class="flnav">
                <li class="flselect">
                    <a href="#" onclick="return false;" title="最新 | 文章" class="pall"></a>
                </li>
                <li>
                    <a href="#" onclick="return false;" title="易阳 | 推荐" class="pgood"></a>
                </li>
                <li>
                    <a href="#" onclick="return false;" title="热评 | 排行" class="pbro"></a>
                </li>
                <li>
                    <a href="#" onclick="return false;" title="收藏 | 排行" class="pfav"></a>
                </li>
            </ul>
            {# flnav ul end #}
        </div>
        {# fenlei-bar end #}

        {# 每个分类的文章 #}
        <div class="newstw">
            {# 最新 #}
            <ul class="sidenews">
                <h2>最新 | 文章</h2>
                {% get_recent_article as recent_article_list %}
                {% for recent_article in recent_article_list %}
                 <li>
                        <i><img src="{{ MEDIA_URL }}{{ recent_article.a_pre_img }}"></i>
                        <p>
                            <a href="{% url 'lwd:blog_detail' recent_article.a_id %}">{{ recent_article.a_title }}</a>
                        </p>
                        <span>{{ recent_article.a_create_time }}</span>
                    </li>
                {% empty %}
                    <p style="margin-top: 10px;margin-bottom: 10px;color: red;font-size: 17px">暂无最新文章哟！</p>
                {% endfor %}
            </ul>
            {# 最新文章end #}

            {# 易阳|推荐 #}
            <ul class="sidenews">
                <h2>易阳 | 推荐</h2>
                {% get_recommend_article as recommend_article_list %}
                {% for recommend_article in recommend_article_list %}
                 <li>
                        <i><img src="{{ MEDIA_URL }}{{ recommend_article.a_pre_img }}"></i>
                        <p>
                            <a href="{% url 'lwd:blog_detail' recommend_article.a_id %}">{{ recommend_article.a_title }}</a>
                        </p>
                        <span>{{ recommend_article.a_create_time }}</span>
                    </li>
                {% empty %}
                    <p style="margin-top: 10px;margin-bottom: 10px;color: red;font-size: 17px">暂无推荐文章哟！</p>
                {% endfor %}
            </ul>
            {# 易阳|推荐 end #}

            {# 热评 排行 #}
            <ul class="sidenews">
                <h2>热评 | 排行</h2>
                {% get_hot_comment_article as hot_comment_article_list %}
                {% for hot_comment_article in hot_comment_article_list %}
                 <li>
                        <i><img src="{{ MEDIA_URL }}{{ hot_comment_article.a_pre_img }}"></i>
                        <p>
                            <a href="{% url 'lwd:blog_detail' hot_comment_article.a_id %}">{{ hot_comment_article.a_title }}</a>
                        </p>
                        <span>{{ hot_comment_article.a_create_time }}</span>
                    </li>
                {% empty %}
                    <p style="margin-top: 10px;margin-bottom: 10px;color: red;font-size: 17px">暂无热评文章哟！</p>
                {% endfor %}

            </ul>
            {# 热评 排行 end #}

            {# 收藏 排行 #}
            <ul class="sidenews">
                <h2>收藏 | 排行</h2>
               {% get_collect_article as collect_article_list %}
                {% for collect_article in collect_article_list %}
                 <li>
                        <i><img src="{{ MEDIA_URL }}{{ collect_article.a_pre_img }}"></i>
                        <p>
                            <a href="{% url 'lwd:blog_detail' collect_article.a_id %}">{{ collect_article.a_title }}</a>
                        </p>
                        <span>{{ collect_article.a_create_time }}</span>
                    </li>
                {% empty %}
                    <p style="margin-top: 10px;margin-bottom: 10px;color: red;font-size: 17px">暂无热评文章哟！</p>
                {% endfor %}

            </ul>
            {# 收藏排行 end #}

        </div>
        {# newstw end #}

        {# 归档功能 #}
        <div class="archives">
            <h2 class="hometitle"><i class="fa fa-th-list"></i> 博客归档</h2>
            {% archives as date_list %}
            <ul>
                {% for date in date_list %}
                    <li class="archives-li">
                        <a href="{% url 'lwd:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                    </li>
                {% empty %}
                    <p style="margin-top: 15px;margin-bottom: 15px;color: red;font-size: 17px">暂无归档！</p>
                {% endfor %}
            </ul>
        </div>

        {# 关于本站 #}
        <div class="about">
            <h2 class="hometitle"><i class="fa fa-th-list"></i> 关于本站</h2>
            <ul>
                <div class="avatar">
                    {# 头像 #}
                    <img src="{% static 'index/images/about/my_img.jpg' %}" title="李易阳" alt="李易阳">
                </div>
                <p class="abname"><a class="home-to-about_me" href="{% url 'lwd:about_me' %}">Lwd | 李易阳</a></p>
                <p class="abtext">
                    李易阳，一个90后全能优质程序员，上得了厅堂，下得了厨房。编得了程序，写得了小说，斗得过流氓。
                </p>
                {# 微博 #}
                <li>
                    <a class="weibo_ico" href="https://www.weibo.com/5715190968" target="_blank"></a>
                </li>
                {# qq #}
                <li class="qq_two_code">
                    <a class="qq_ico" href="" onclick="return false;"></a>
                    <img src="{% static 'index/images/about/lwd_qq_two_code.jpg' %}"/>
                </li>
                {# github #}
                <li>
                    <a class="github_ico" href="https://github.com/YddVae" target="_blank"></a>
                </li>
                {# 微信 #}
                <li class="wx_two_code">
                    <a class="wx_ico" href="" onclick="return false;"></a>
                    <img src="{% static 'index/images/about/lwd_wx_two_code.jpg' %}"/>
                </li>
            </ul>
        </div>
        {# 关于本站 end #}

        {# vip广告位01 #}
        <div id="vip-ad">
            <h2 class="hometitle" style="color: red;"><i class="fa fa-th-list"></i> VIP广告</h2>
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% get_ad_banner as ad_banners %}
                    {% for ad_banner in ad_banners %}
                        {#  轮播图第一张  #}
                        <a href="{{ ad_banner.ab_link }}" class="swiper-slide"
                           style="background-image:url({{ MEDIA_URL }}{{ ad_banner.ab_img_upload }})">
                        <span class="imginfo"
                              style="bottom: 10%;color: red;font-size: 1.25rem;z-index: auto;">{{ ad_banner.b_info_content }}</span>
                        </a>
                    {% endfor %}
                </div>
                {#  Add Pagination  #}
                <div class="swiper-pagination"></div>
            </div>
        </div>
        {# 广告位 end #}

        {# 推荐栏目 #}
        <div class="tjlm">
            <h2 class="hometitle"><i class="fa fa-th-list"></i> 推荐栏目</h2>
            <ul>
                <li>
                    <a href="#">网站开发</a>
                </li>
                <li>
                    <a href="#">网络爬虫</a>
                </li>
                <li>
                    <a href="#">数据分析</a>
                </li>
                <li>
                    <a href="#">机器学习</a>
                </li>
                <li>
                    <a href="#">HTML+CSS</a>
                </li>
                <li>
                    <a href="#">JS编程</a>
                </li>
                <li>
                    <a href="#">Vue.js</a>
                </li>
                <li>
                    <a href="#">Node.js</a>
                </li>
            </ul>
        </div>
        {# 推荐目录 end #}

        {# 友情链接 #}
        <div class="links">
            <h2 class="hometitle"><i class="fa fa-th-list"></i> 友情链接</h2>
            <ul>
                <li>
                    <a href="http://www.asc.jx.cn/">皇家理工应科院</a>
                </li>
                <li>
                    <a href="https://cuijiahua.com/">静觅 | 博客</a>
                </li>
                <li>
                    <a href="https://www.jianshu.com/">简书 | 创作</a>
                </li>
                <li>
                    <a href="https://www.mi.com/">小米商城</a>
                </li>
            </ul>
            {# 友情链接 ul end #}
        </div>
        {# 友情链接 end #}

        {# 广告位02 #}
        <div class="ad">
            <h2 class="hometitle"><i class="fa fa-th-list"></i> 广而告之</h2>
            <a href="http://www.asc.jx.cn/" target="_blank" class="ad-a">
                <img src="{% static 'index/images/ad_img/jxlg.png' %}">
                <span class="imginfo"
                      style="bottom: 2%;color: white;font-size: 1.25rem;z-index: auto;">皇家理工应科院欢迎您</span>
            </a>
        </div>
        {# 广告位 end #}
    </aside>
    {# 侧边栏信息 end #}


{% endblock %}

{# cd-top，cd-bottom #}
{% block footer_sub %}
    <ul id="scroll">
        {# 向上 #}
        <li class="lwd-cd-top">
            <a href="#" style="background-color: #ff5e5c;">
                <i class="fa fa-arrow-up"></i>
            </a>
        </li>
        {# 向下 #}
        <li class="lwd-cd-bottom">
            <a href="#" style="background-color: #ff9531;">
                <i class="fa fa-arrow-down"></i>
            </a>
        </li>

        <li>
            <input type="button" name="" id="" value="简" style="background-color: burlywood" onclick="zh_tran('s');"/>
        </li>

        {# 繁体 #}
        <li>
            <input type="button" name="" id="" value="繁" style="background-color: #aec534;" onclick="zh_tran('t');"/>
        </li>

        {# 微信 #}
        <li class="lwd-scroll-wechat">
            <a href="#" style="background-color: #3caf33;">
                <i class="fa fa-wechat"></i>
            </a>
            <img src="{% static 'index/images/about/lwd_wx_two_code.jpg' %}"/>
        </li>
    </ul>
{% endblock %}

{# 导入额外的JS#}
{% block EXTJS %}
    <script src="{% static 'index/js/index.js' %}" type="text/javascript" charset="utf-8"></script>

    <script>
        $("#starlist li:first-child a").attr("id", "");
    </script>
{% endblock %}

templates/base.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {# 头部元信息 #}
    <meta name="keywords" content="李易阳，个人博客 | 问世间情为何物 直教人生死相许">
    <meta name="description" content="李易阳，个人博客，一个提供编程技术相关文章的美男子"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {# 导入字体图标 #}
    <link rel="stylesheet" href="{% static 'base/css/font_awesome/css/font-awesome.min.css' %}">
    {# 导入swiper.css #}
    <link rel="stylesheet" href="{% static 'base/css/swiper.min.css' %}">
    {# 导入重置a li 等样式 #}
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    {# 导入base.css #}
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    {# 屏幕的适应尺寸 #}
    <link rel="stylesheet" href="{% static 'base/css/fit_size.css' %}">

    {#  标题图标  #}
    <link rel="shortcut icon" href="{% static 'base/images/blog_title.ico' %}" type="image/x-icon">
    {# 标题 #}
    {% block title %}
    {% endblock %}

    {#   样式表#}
    {% block EXTCSS %}
    {% endblock %}
</head>
<body>

{# 头部#}
{% block header %}
    {# 头部标记header #}
    <header id="header">
        {# 导航工具栏 #}
        <div class="navbar">
            <div class="topbox">
                <p class="welcome">您好，欢迎您访问李易阳 | 个人博客，问世间情为何物 直教人生死相许！</p>
                {# 搜索栏 #}
                <div class="searchbox">
                    <div id="search_bar" class="search_bar">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            {% csrf_token %}
                            {# 搜索框 #}
                            <input class="search_text" placeholder="请输入关键词搜索" type="search" name="q" id="search_text">
                            {# 搜索按钮 #}
                            <button type="submit"><span id="search_ico"></span></button>

                        </form>
                    </div>
                    {# end search_bar #}
                </div>
                {# end searchbox #}
            </div>
            {# end topbox #}
        </div>
        {# end navbar #}

        {# 导航栏--内容 #}
        <div class="header-navigation">
            <nav>
                {# 导航栏内容--左边--logo #}
                <div class="logo">
                    <a href="{% url 'lwd:index' %}">❤Lwd's Blog❤</a>
                </div>

                {# 自动折叠三条横杠 #}
                <h2 id="mnavh"><span class="navicon"></span></h2>

                {# 首页，等内容 #}
                <ul id="starlist">
                    {#  首页  #}
                    <li>
                        <a href="{% url 'lwd:index' %}" id="selected"><i class="fa fa-home fa-fw"></i> Home</a>
                    </li>

                    {# Python编程 #}
                    <li class="menu">
                        <a href="#"><i class="fa fa-paypal"></i> Python</a>
                        <ul class="sub">
                            {% get_python_category as ptyon_category_list %}
                            {% for category_name in ptyon_category_list %}
                                    <li>
                                        <a href="{% url 'lwd:article_category' category_name.id %}">{{ category_name.category_name }}</a>
                                    </li>
                            {% empty %}
                                <li><a href="#">暂无分类</a></li>
                            {% endfor %}
                        </ul>
                        {#  python sub end  #}
                    </li>

                    {# 技术分享 #}
                    <li class="menu">
                        <a href="#"><i class="fa fa-simplybuilt"></i> Share</a>
                        <ul class="sub">
                            {% get_share_category as share_category_list %}
                            {% for category_name in share_category_list %}
                                    <li>
                                        <a href="{% url 'lwd:article_category' category_name.id %}">{{ category_name.category_name }}</a>
                                    </li>
                            {% empty %}
                                <li><a href="#">暂无分类</a></li>
                            {% endfor %}
                        </ul>
                    </li>

                    {# 其他分类 #}
                    <li class="menu">
                        <a href="#"><i class="fa fa-modx"></i> Other</a>
                        <ul class="sub">
                            {% get_other_category as other_category_list %}
                            {% for category_name in other_category_list %}
                                <li>
                                    <a href="{% url 'lwd:article_category' category_name.id %}">{{ category_name.category_name }}</a>
                                </li>
                            {% empty %}
                                <li><a href="#">暂无分类</a></li>
                            {% endfor %}

                        </ul>
                    </li>

                    {# 有token在就是登录后的样式 #}
                    {% if token %}
                        {# 用户信息 #}
                        <li class="user-info-menu">
                            <a href="#"><img src="{{ MEDIA_URL }}{{ user_token.u_img }}" alt="" title=""></a>
                            <ul class="user-info-sub">
                                <li>
                                    <i class="fa fa-user"></i>
                                    <a href="{% url 'lwd:user_home' user_token.u_id %}"
                                       onclick="publish_dfrat_session_storage('publish')"> 我的主页</a>
                                </li>
                                <li>
                                    <i class="fa fa-star"></i>
                                    <a href="{% url 'lwd:collect_like' user_token.u_id %}"
                                       onclick="collect_like_session_storage('collect')"> 收藏的文章</a>
                                </li>
                                <li>
                                    <i class="fa fa-heart"></i>
                                    <a href="{% url 'lwd:collect_like' user_token.u_id %}"
                                       onclick="collect_like_session_storage('like')"> 喜欢的文章</a>
                                </li>
                                <li>
                                    <i class="fa fa-list-ol"></i>
                                    <a href="#"> 文章分类</a>
                                </li>
                                <li>
                                    <i class="fa fa-cog"></i>
                                    <a href="{% url 'lwd:user_setting' user_token.u_id %}"> 设置</a>
                                </li>
                                <li>
                                    <i class="fa fa-hand-o-right"></i>
                                    <a href="{% url 'lwd:quit' %}"> 退出</a>
                                </li>
                            </ul>
                        </li>
                        {# token不在 #}
                    {% else %}
                        {# 登录 #}
                        <li>
                            <a href="{% url 'lwd:login' %}" onclick="login_register_session_storage('login')">
                                <i class="fa fa-user-circle-o"></i>
                                登录
                            </a>
                        </li>
                        {# 登录end #}

                        {#  注册  #}
                        <li>
                            <a href="{% url 'lwd:register' %}" onclick="login_register_session_storage('register')"><i
                                    class="fa fa-user-circle"></i>
                                注册</a>
                        </li>
                        {# 注册end #}
                    {% endif %}

                    {% if token %}
                        <li>
                            <a href="{% url 'lwd:write' %}" id="lwd-write-article"><i class="fa fa-pencil-square-o"></i>
                                写博客</a>
                        </li>
                    {% else %}
                        {#  写博客  #}
                        <li>
                            <a href="{% url 'lwd:login' %}" id="lwd-write-article"
                               onclick="login_register_session_storage('login')"><i class="fa fa-pencil-square-o"></i>
                                写博客</a>
                        </li>
                    {% endif %}

                </ul>
                {#  starlist end  #}
            </nav>
        </div>
    </header>
    {# end header #}
{% endblock %}


{# 主体内容 #}
<div class="wrapper">
    {% block content %}
    {% endblock %}
</div>

{# 其他内容 #}
{% block content_sub %}
{% endblock %}


{# 尾部#}
{% block footer %}
    {# footer 开始 #}
    <footer>
        <div class="footer">
            <div class="wxbox">
                {# 微信二维码 #}
                <ul>
                    <li>
                        <img src="{% static 'base/images/lwd_wx_two_code.jpg' %}" title="加我微信有惊喜哟" alt="加我微信有惊喜哟">
                        <span>李易阳的微信</span>
                    </li>
                    <li>
                        <img src="{% static 'base/images/lwd_qq_two_code.jpg' %}" title="加我QQ有惊喜哟" alt="加我QQ有惊喜哟">
                        <span>李易阳的QQ</span>
                    </li>
                </ul>
            </div>
            {# 本站简介 #}
            <div class="bzjj">
                <h2>本站简介</h2>
                <p>李易阳 | 个人博客，是一个专注于编写IT技术博客或者文章的网站，网站的开发作者是一个帅气、阳光的程序员，他上得了厅堂、下得了厨房、解决得了bug、写得了文章，还斗得过流氓。</p>
            </div>
            {# 其他信息，网站的版权，运行时间 #}
            <div class="other">
                <h2>网站版权</h2>
                <p>
                    <!--时间-->
                <div id="colophon" class="site-footer" role="contentinfo">
                    <div class="site-info">
                        Copyright © 2019-2020&nbsp;&nbsp;赣ICP备17017404号-1
                        <span class="add-info">
									<br/>
									网站稳定运行：
								</span>
                        <span id="span_dt_dt"></span>
                    </div>
                </div>
                </p>
                <p>&nbsp;</p>
                <p></p>
            </div>
        </div>
    </footer>
    {# footer end #}
{% endblock %}

{# 底部或许还可以有其他内容，比如scroll 向上向下 #}
{% block footer_sub %}
{% endblock %}




{# 默认需要的js #}
<script src="{% static 'base/js/jquery.min.js' %}"></script>
<script src="{% static 'base/js/jquery.cookie.js' %}"></script>
<script src="{% static 'base/js/bootstrap.min.js' %}"></script>
<script src="{% static 'base/js/swiper.min.js' %}"></script>
<script src="{% static 'base/js/hc-sticky.js' %}"></script>
<script src="{% static 'base/js/language.js' %}"></script>
<script src="{% static 'base/js/lwd_time.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>

{# 导入窝巢特效 #}
<script type="text/javascript" color="0,0,255" opacity='0.7' zIndex="-2" count="99"
        src="//cdn.bootcss.com/canvas-nest.js/1.0.1/canvas-nest.min.js"></script>


{# 导入额外的JS#}
{% block EXTJS %}
{% endblock %}

</body>
</html>

templates/pagination.html
{% load static %}


<div class="pagelist">
    <ul>
        {% if article_page %}
            {% if article_page.has_previous %}
                <li>
                    <a href="?page={{ article_page.previous_page_number }}">
                        <i class="fa fa-arrow-left"></i>
                    </a>
                </li>
            {% else %}
                <li style="background-color: #f9f2f4">
                    <a href="" title="没有上一页" onclick="return false;">
                        <i class="fa fa-arrow-left"></i>
                    </a>
                </li>
            {% endif %}

            {% for page in article_page.paginator.page_range %}
                {% if article_page.number == page %}
                    <li class="active">
                        <a href="?page={{ page }}"> {{ page }} </a>
                    </li>
                {% else %}
                    <li>
                        <a href="?page={{ page }}"> {{ page }} </a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if article_page.has_next %}
                <li>
                    <a href="?page={{ article_page.next_page_number }}" aria-label="Next">
                        <i class="fa fa-arrow-right"></i>
                    </a>
                </li>
            {% else %}
                <li style="background-color: #f9f2f4">
                    <a href="" title="没有下一页" onclick="return false;">
                        <i class="fa fa-arrow-right"></i>
                    </a>
                </li>
            {% endif %}
        {% endif %}
    </ul>

</div>